// 参拝ログ バックアップ / 復元
(() => {
  'use strict';
  const DB_NAME='goshuin-zukan', DB_VERSION=1, STORE_NAME='visitLogs';
  const openDb=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains(STORE_NAME)){const s=d.createObjectStore(STORE_NAME,{keyPath:'id'});s.createIndex('visitDate','visitDate',{unique:false});s.createIndex('createdAt','createdAt',{unique:false});}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
  const blobToDataURL=blob=>new Promise((resolve,reject)=>{if(!blob){resolve(null);return;}const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
  const dataURLToBlob=data=>{if(!data)return null;const [h,b]=data.split(',');const type=(h.match(/data:(.*?);base64/)||[])[1]||'application/octet-stream';const bin=atob(b),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type});};
  async function getAll(){const db=await openDb();const rows=await new Promise((res,rej)=>{const r=db.transaction(STORE_NAME,'readonly').objectStore(STORE_NAME).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});db.close();return rows;}
  async function exportBackup(){try{const rows=await getAll();const records=[];for(const r of rows){const copy={...r};copy.photoData=await blobToDataURL(r.photo);delete copy.photo;if(Array.isArray(r.photos)){copy.photosData=[];for(const p of r.photos)copy.photosData.push(await blobToDataURL(p));delete copy.photos;}records.push(copy);}const payload={format:'goshuin-zukan-backup',version:1,exportedAt:new Date().toISOString(),records};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`goshuin-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);alert(`参拝記録 ${records.length}件を書き出しました。`);}catch(e){console.error(e);alert('バックアップを書き出せませんでした。');}}
  async function importBackup(file){try{const payload=JSON.parse(await file.text());if(payload?.format!=='goshuin-zukan-backup'||!Array.isArray(payload.records))throw new Error('invalid backup');if(!confirm(`バックアップ ${payload.records.length}件を復元します。\n同じIDの記録はバックアップ内容で更新されます。よろしいですか？`))return;const db=await openDb();const tx=db.transaction(STORE_NAME,'readwrite'),store=tx.objectStore(STORE_NAME);for(const raw of payload.records){const r={...raw};r.photo=dataURLToBlob(r.photoData);delete r.photoData;if(Array.isArray(r.photosData)){r.photos=r.photosData.map(dataURLToBlob).filter(Boolean);delete r.photosData;if(!r.photo&&r.photos.length)r.photo=r.photos[0];}store.put(r);}await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error);});db.close();alert(`参拝記録 ${payload.records.length}件を復元しました。\n画面を再読み込みします。`);location.reload();}catch(e){console.error(e);alert('このファイルは御朱印アプリのバックアップとして読み込めませんでした。');}}
  function install(){const heading=document.querySelector('.log-list-heading');if(!heading||document.getElementById('backup-controls'))return;const box=document.createElement('div');box.id='backup-controls';box.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin:8px 0 12px;';box.innerHTML='<button type="button" class="jinja-btn" id="backup-export">💾 バックアップを書き出す</button><button type="button" class="jinja-btn" id="backup-import">📂 バックアップから復元</button><input type="file" id="backup-file" accept="application/json,.json" hidden>';heading.insertAdjacentElement('afterend',box);box.querySelector('#backup-export').addEventListener('click',exportBackup);box.querySelector('#backup-import').addEventListener('click',()=>box.querySelector('#backup-file').click());box.querySelector('#backup-file').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importBackup(f);e.target.value='';});}
  document.addEventListener('DOMContentLoaded',install);if(document.readyState!=='loading')install();
})();