// ============================================================
// User Shrine Registration
// 神社データは window.jinjaData に統一し、source_type=official/user で出所を区別する。
// Kim追加分は端末内に保持し、起動時に同じ神社データへ復元する。
// ============================================================
(() => {
    'use strict';
    const STORAGE_KEY = 'goshuin-zukan:user-shrines:v1';
    let addMode = false, selectedLatLng = null, draftMarker = null, mapClickBound = false, initialized = false;
    document.addEventListener('DOMContentLoaded', waitUntilReady);
    if (document.readyState !== 'loading') waitUntilReady();
    function waitUntilReady(){ if(initialized)return; if(!window.map||!Array.isArray(window.jinjaData)||!window.jinjaData.length){setTimeout(waitUntilReady,250);return;} initialized=true; tagOfficialShrines(); mergeSavedShrines(); installAddButton(); installModal(); bindMapClick(); refreshMap(); }
    function tagOfficialShrines(){ window.jinjaData.forEach(s=>{if(!s.source_type)s.source_type='official';}); }
    function loadSavedShrines(){ try{const r=localStorage.getItem(STORAGE_KEY);const p=r?JSON.parse(r):[];return Array.isArray(p)?p:[];}catch(e){console.warn('[UserShrine] load failed',e);return [];} }
    function saveAllUserShrines(rows){ localStorage.setItem(STORAGE_KEY,JSON.stringify(rows)); }
    function mergeSavedShrines(){ const saved=loadSavedShrines(); if(!saved.length)return; const byId=new Map(window.jinjaData.map(s=>[s.id,s])); saved.forEach(s=>{s.source_type='user';byId.set(s.id,s);}); window.jinjaData=Array.from(byId.values()); }
    function installAddButton(){ const w=document.querySelector('.header-search'); if(!w||document.getElementById('add-shrine-btn'))return; const b=document.createElement('button'); b.type='button'; b.id='add-shrine-btn'; b.className='add-shrine-btn'; b.textContent='＋ 神社を追加'; b.title='地図上に神社を追加する'; b.addEventListener('click',()=>addMode?cancelAddMode():startAddMode()); w.prepend(b); }
    function installModal(){ if(document.getElementById('user-shrine-modal'))return; const m=document.createElement('div'); m.id='user-shrine-modal'; m.className='user-shrine-modal'; m.hidden=true; m.innerHTML=`<div class="user-shrine-dialog" role="dialog" aria-modal="true" aria-labelledby="user-shrine-title"><button type="button" id="user-shrine-close" class="user-shrine-close">×</button><h2 id="user-shrine-title">⛩ 神社を追加</h2><p class="user-shrine-help">PINの位置に神社を登録します。</p><form id="user-shrine-form"><label>神社名 <span>必須</span><input id="user-shrine-name" type="text" required autocomplete="off" placeholder="例：○○神社"></label><label>よみ<input id="user-shrine-yomi" type="text" autocomplete="off"></label><label>住所<input id="user-shrine-address" type="text" autocomplete="off"></label><label>メモ<textarea id="user-shrine-memo" rows="3"></textarea></label><div class="user-shrine-position" id="user-shrine-position"></div><div class="user-shrine-actions"><button type="button" id="user-shrine-cancel">キャンセル</button><button type="submit" class="jinja-btn">この神社を保存</button></div><p id="user-shrine-status" aria-live="polite"></p></form></div>`; document.body.appendChild(m); document.getElementById('user-shrine-close')?.addEventListener('click',cancelAddMode); document.getElementById('user-shrine-cancel')?.addEventListener('click',cancelAddMode); document.getElementById('user-shrine-form')?.addEventListener('submit',saveShrine); m.addEventListener('click',e=>{if(e.target===m)cancelAddMode();}); }
    function bindMapClick(){ if(mapClickBound||!window.map)return; mapClickBound=true; window.map.on('click',e=>{if(!addMode)return; selectedLatLng=e.latlng; showDraftMarker(selectedLatLng); openForm();}); }
    function startAddMode(){ addMode=true; selectedLatLng=null; clearDraftMarker(); document.body.classList.add('shrine-add-mode'); const b=document.getElementById('add-shrine-btn'); if(b)b.textContent='× 追加をやめる'; setMapHint('地図上の神社の位置をクリックしてください'); }
    function cancelAddMode(){ addMode=false; selectedLatLng=null; clearDraftMarker(); document.body.classList.remove('shrine-add-mode'); const b=document.getElementById('add-shrine-btn'); if(b)b.textContent='＋ 神社を追加'; const m=document.getElementById('user-shrine-modal'); if(m)m.hidden=true; setMapHint(''); }
    function setMapHint(text){ let h=document.getElementById('user-shrine-map-hint'); if(!h){h=document.createElement('div');h.id='user-shrine-map-hint';h.className='user-shrine-map-hint';document.getElementById('map-view')?.appendChild(h);} h.textContent=text; h.hidden=!text; }
    function showDraftMarker(ll){ clearDraftMarker(); if(!window.map||typeof L==='undefined')return; const icon=L.divIcon({className:'user-shrine-draft-wrap',html:'<div class="user-shrine-draft-pin"><span>＋</span></div>',iconSize:[38,38],iconAnchor:[19,34]}); draftMarker=L.marker([ll.lat,ll.lng],{icon,zIndexOffset:2000}).addTo(window.map); }
    function clearDraftMarker(){ if(draftMarker&&window.map)window.map.removeLayer(draftMarker); draftMarker=null; }
    function openForm(){ const m=document.getElementById('user-shrine-modal'); if(!m||!selectedLatLng)return; document.getElementById('user-shrine-form')?.reset(); const p=document.getElementById('user-shrine-position'); if(p)p.textContent=`PIN：${selectedLatLng.lat.toFixed(6)}, ${selectedLatLng.lng.toFixed(6)}`; m.hidden=false; setTimeout(()=>document.getElementById('user-shrine-name')?.focus(),0); }
    function saveShrine(e){ e.preventDefault(); if(!selectedLatLng)return; const name=String(document.getElementById('user-shrine-name')?.value||'').trim(); if(!name)return; const yomi=String(document.getElementById('user-shrine-yomi')?.value||'').trim(), address=String(document.getElementById('user-shrine-address')?.value||'').trim(), memo=String(document.getElementById('user-shrine-memo')?.value||'').trim(), now=new Date().toISOString(), id=createUserShrineId(), lat=Number(selectedLatLng.lat.toFixed(7)), lng=Number(selectedLatLng.lng.toFixed(7)); const s={id,name,yomi,former_shrine_rank:'',shikinaisha_type:'',ichinomiya_name:'',province:'',county:'',prefecture:'',city:'',address,lat:String(lat),lng:String(lng),gmap_url:`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`,main_god_ids:'',sub_god_ids:'',description:memo,source_type:'user',created_at:now,updated_at:now}; try{const saved=loadSavedShrines();saved.push(s);saveAllUserShrines(saved);window.jinjaData.push(s);cancelAddMode(); if(window.map)window.map.setView([lat,lng],Math.max(window.map.getZoom(),15)); setTimeout(()=>{refreshMap();window.selectJinja?.(id);},100);}catch(err){console.error('[UserShrine] save failed',err); const st=document.getElementById('user-shrine-status');if(st)st.textContent='保存できませんでした。';} }
    function createUserShrineId(){return `U${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,6).toUpperCase()}`;}
    function refreshMap(){ if(typeof window.renderJinjaList==='function')window.renderJinjaList(); else if(typeof window.renderMarkers==='function')window.renderMarkers(); }
})();
